/**
 * ElectroMart Custom Product Seeder
 * Run with: node seedCustomProducts.js
 * 
 * This script adds all custom products from the /public folder.
 * Prices are set to ₦1,000 placeholder — update them in the Inventory tab.
 */

const mongoose = require('mongoose');
require('dotenv').config();

const Product = require('./models/Product');

const MONGO_URI = process.env.MONGO_URI;

const customProducts = [
  // ─── LIGHTING & FIXTURES ────────────────────────────────────────────
  {
    name: '300W AKT Separate Panel Solar Light',
    brand: 'AKT',
    price: 1000,
    category: 'Lighting & Fixtures',
    image: '300watts akt separate panel solar light.jpeg',
    description: 'High-output 300W solar flood light with a separate solar panel. Ideal for large outdoor spaces, compounds, and security lighting.',
    rating: 0, reviews: 0, stockQuantity: 10,
  },
  {
    name: '500W AKT Separate Panel Solar Light',
    brand: 'AKT',
    price: 1000,
    category: 'Lighting & Fixtures',
    image: '500watts akt separate panel solar light .jpeg',
    description: 'Premium 500W solar flood light with a detachable solar panel. Perfect for warehouses, large estates, and commercial outdoor lighting.',
    rating: 0, reviews: 0, stockQuantity: 10,
  },
  {
    name: '6W COB Bulb (Blue)',
    brand: 'Generic',
    price: 1000,
    category: 'Lighting & Fixtures',
    image: '6Watts COB light Blue (2).jpeg',
    description: 'Energy-saving 6W COB light bulb with a cool blue daylight tone. Great for offices, kitchens, and ambient lighting.',
    rating: 0, reviews: 0, stockQuantity: 50,
  },
  {
    name: '6W COB Bulb (Yellow)',
    brand: 'Generic',
    price: 1000,
    category: 'Lighting & Fixtures',
    image: '6Watts COB light Yellow (1).jpeg',
    description: 'Energy-saving 6W COB light bulb with a warm yellow tone. Perfect for bedrooms, living rooms, and cozy ambiances.',
    rating: 0, reviews: 0, stockQuantity: 50,
  },
  {
    name: 'AKT 100W Flood Light',
    brand: 'AKT',
    price: 1000,
    category: 'Lighting & Fixtures',
    image: 'AKT 100 watt Flood Light.jpeg',
    description: 'Heavy-duty 100W LED flood light for outdoor security and area illumination. Weatherproof and energy-efficient.',
    rating: 0, reviews: 0, stockQuantity: 15,
  },
  {
    name: 'AKT Flood LED Light',
    brand: 'AKT',
    price: 1000,
    category: 'Lighting & Fixtures',
    image: 'AKT Flood Led Light.jpeg',
    description: 'AKT branded LED flood light for bright and efficient outdoor illumination.',
    rating: 0, reviews: 0, stockQuantity: 20,
  },
  {
    name: 'AKT LED Lightning 40W',
    brand: 'AKT',
    price: 1000,
    category: 'Lighting & Fixtures',
    image: 'AKT Led Lightning 40watts.jpeg',
    description: '40W AKT LED light fixture. Energy-efficient replacement for fluorescent tubes in homes and commercial settings.',
    rating: 0, reviews: 0, stockQuantity: 25,
  },
  {
    name: 'AKT Lightning Fixture',
    brand: 'AKT',
    price: 1000,
    category: 'Lighting & Fixtures',
    image: 'AKT Lightning .jpeg',
    description: 'Versatile AKT LED lighting fixture suitable for indoor and outdoor use.',
    rating: 0, reviews: 0, stockQuantity: 20,
  },
  {
    name: 'Fancy Wall Light',
    brand: 'Generic',
    price: 1000,
    category: 'Lighting & Fixtures',
    image: 'Fancy Wall Light.jpeg',
    description: 'Decorative fancy wall light for interior design. Adds an elegant touch to living rooms, corridors, and bedrooms.',
    rating: 0, reviews: 0, stockQuantity: 15,
  },
  {
    name: 'Hanging Pendant Light',
    brand: 'Generic',
    price: 1000,
    category: 'Lighting & Fixtures',
    image: 'Hanging Light.jpeg',
    description: 'Modern hanging pendant light perfect for dining areas, kitchens, and decorative ceiling installations.',
    rating: 0, reviews: 0, stockQuantity: 12,
  },
  {
    name: 'LED Solar Flood Light',
    brand: 'Generic',
    price: 1000,
    category: 'Lighting & Fixtures',
    image: 'LED Solar Flood Light.jpeg',
    description: 'Solar-powered LED flood light with automatic dusk-to-dawn activation. No electricity bill, zero wiring required.',
    rating: 0, reviews: 0, stockQuantity: 20,
  },
  {
    name: 'LED Bulb',
    brand: 'Generic',
    price: 1000,
    category: 'Lighting & Fixtures',
    image: 'LED bulb.jpeg',
    description: 'Standard LED bulb with high luminosity and long lifespan. Energy-efficient replacement for incandescent bulbs.',
    rating: 0, reviews: 0, stockQuantity: 100,
  },
  {
    name: 'LED SMD Rope Light',
    brand: 'Generic',
    price: 1000,
    category: 'Lighting & Fixtures',
    image: 'Led Smd Rope Light.jpeg',
    description: 'Flexible LED SMD rope light for decorative purposes. Ideal for accent lighting, events, and creative setups.',
    rating: 0, reviews: 0, stockQuantity: 30,
  },
  {
    name: 'Wall Light',
    brand: 'Generic',
    price: 1000,
    category: 'Lighting & Fixtures',
    image: 'Wall Light .jpeg',
    description: 'Simple and modern LED wall light fixture for corridors, porches, and outdoor use.',
    rating: 0, reviews: 0, stockQuantity: 20,
  },

  // ─── FANS & COOLING ────────────────────────────────────────────────
  {
    name: 'AVA Rechargeable Wall Fan',
    brand: 'AVA',
    price: 1000,
    category: 'Fans & Cooling',
    image: 'AVA Wall Fan.jpeg',
    description: 'AVA rechargeable wall-mounted fan. Suitable for areas with unreliable power. Long battery life with multiple speed settings.',
    rating: 0, reviews: 0, stockQuantity: 15,
  },
  {
    name: 'Binatone Standing Fan',
    brand: 'Binatone',
    price: 1000,
    category: 'Fans & Cooling',
    image: 'Binatone Standing Fan.jpeg',
    description: 'Binatone branded standing pedestal fan with adjustable height and multiple speed settings. Silent motor.',
    rating: 0, reviews: 0, stockQuantity: 20,
  },
  {
    name: 'Binatone Standing Fan TS 2020',
    brand: 'Binatone',
    price: 1000,
    category: 'Fans & Cooling',
    image: 'Binatone Standing fan TS 2020.jpeg',
    description: 'Binatone TS 2020 model standing fan. Powerful airflow with quiet operation, perfect for homes and offices.',
    rating: 0, reviews: 0, stockQuantity: 15,
  },
  {
    name: 'Black Wall Standing Fan',
    brand: 'Generic',
    price: 1000,
    category: 'Fans & Cooling',
    image: 'Black Wall Standing FAN.jpeg',
    description: 'Sleek black standing fan that doubles as a wall fan. Space-saving design with powerful airflow.',
    rating: 0, reviews: 0, stockQuantity: 10,
  },
  {
    name: 'Century Rechargeable Fan 2',
    brand: 'Century',
    price: 1000,
    category: 'Fans & Cooling',
    image: 'Century Rechargeable Fan 2.jpeg',
    description: 'Century rechargeable standing fan with built-in battery for use during power outages. Multiple speed settings.',
    rating: 0, reviews: 0, stockQuantity: 15,
  },
  {
    name: 'Century Rechargeable Standing Fan',
    brand: 'Century',
    price: 1000,
    category: 'Fans & Cooling',
    image: 'Century Rechargeable standing Fan.jpeg',
    description: 'Premium Century rechargeable standing fan with long-lasting battery, LED lighting, and USB charging ports.',
    rating: 0, reviews: 0, stockQuantity: 15,
  },
  {
    name: 'Century Standing Fan',
    brand: 'Century',
    price: 1000,
    category: 'Fans & Cooling',
    image: 'Century standing fan.jpeg',
    description: 'Classic Century standing fan with robust motor, adjustable height, and 3-speed settings.',
    rating: 0, reviews: 0, stockQuantity: 20,
  },
  {
    name: 'DuraVolt Rechargeable Wall/Table Fan',
    brand: 'DuraVolt',
    price: 1000,
    category: 'Fans & Cooling',
    image: 'DuraVolt Rechargeable Wall Fan or Table.jpeg',
    description: 'Versatile DuraVolt rechargeable fan that works as both a wall-mounted or table fan. Built-in battery for uninterrupted airflow.',
    rating: 0, reviews: 0, stockQuantity: 12,
  },
  {
    name: 'ORL Ceiling Fan',
    brand: 'ORL',
    price: 1000,
    category: 'Fans & Cooling',
    image: 'ORL Ceiling Fan.jpeg',
    description: 'ORL ceiling fan with elegant blade design and multiple speed settings. Perfect for spacious rooms and offices.',
    rating: 0, reviews: 0, stockQuantity: 10,
  },
  {
    name: 'OX Standing Fan',
    brand: 'OX',
    price: 1000,
    category: 'Fans & Cooling',
    image: 'OX Standding fan.jpeg',
    description: 'OX brand heavy-duty standing fan with powerful airflow. Durable motor suitable for 24/7 operation.',
    rating: 0, reviews: 0, stockQuantity: 15,
  },
  {
    name: 'Orbit Standing Fan',
    brand: 'Orbit',
    price: 1000,
    category: 'Fans & Cooling',
    image: 'Orbit fan.jpeg',
    description: 'Orbit standing fan with oscillation feature and quiet operation. Energy-saving motor for everyday use.',
    rating: 0, reviews: 0, stockQuantity: 15,
  },
  {
    name: 'QASA Rechargeable Fan',
    brand: 'QASA',
    price: 1000,
    category: 'Fans & Cooling',
    image: 'QASA Rechargeable fan.jpeg',
    description: 'QASA rechargeable standing fan with built-in battery and LED light. Works for hours after a full charge.',
    rating: 0, reviews: 0, stockQuantity: 12,
  },
  {
    name: 'Rechargeable Fan',
    brand: 'Generic',
    price: 1000,
    category: 'Fans & Cooling',
    image: 'Rechargeable fan.jpeg',
    description: 'Generic rechargeable fan with a built-in battery. Ideal for areas with frequent power outages.',
    rating: 0, reviews: 0, stockQuantity: 20,
  },
  {
    name: 'Solar Rechargeable Fan',
    brand: 'Generic',
    price: 1000,
    category: 'Fans & Cooling',
    image: 'Solar rechargeable fan .jpeg',
    description: 'Solar-powered rechargeable fan. Harness the sun\'s energy to stay cool even during power cuts.',
    rating: 0, reviews: 0, stockQuantity: 10,
  },
  {
    name: 'Solar Rechargeable Fan (Model 2)',
    brand: 'Generic',
    price: 1000,
    category: 'Fans & Cooling',
    image: 'Solar rechargeable fan 2.jpeg',
    description: 'Upgraded solar rechargeable fan with improved battery capacity and faster charging panel.',
    rating: 0, reviews: 0, stockQuantity: 10,
  },
  {
    name: 'Solar Rechargeable Wall Fan (AVA)',
    brand: 'AVA',
    price: 1000,
    category: 'Fans & Cooling',
    image: 'Solar rechargeable wall fan 3 AVA.jpeg',
    description: 'AVA solar rechargeable wall fan. Wall-mountable for space efficiency with solar panel compatibility.',
    rating: 0, reviews: 0, stockQuantity: 8,
  },
  {
    name: 'Standing Fan (Black)',
    brand: 'Generic',
    price: 1000,
    category: 'Fans & Cooling',
    image: 'Standing Fan Black.jpeg',
    description: 'Classic black standing fan with oscillation and adjustable height. Strong airflow for homes and offices.',
    rating: 0, reviews: 0, stockQuantity: 15,
  },

  // ─── SWITCHES & SOCKETS ─────────────────────────────────────────────
  {
    name: 'Double Socket',
    brand: 'Generic',
    price: 1000,
    category: 'Switches & Sockets',
    image: 'Double-Socket .jpeg',
    description: 'Heavy-duty double wall socket for high-usage areas. Suitable for all standard electrical plugs.',
    rating: 0, reviews: 0, stockQuantity: 50,
  },
  {
    name: 'Gold Single Socket & Switch',
    brand: 'Generic',
    price: 1000,
    category: 'Switches & Sockets',
    image: 'Gold Single Socket & Switch.jpeg',
    description: 'Premium gold-finish single socket and switch plate for a luxurious interior aesthetic.',
    rating: 0, reviews: 0, stockQuantity: 30,
  },
  {
    name: 'Single Socket & Switch',
    brand: 'Generic',
    price: 1000,
    category: 'Switches & Sockets',
    image: 'Single Socket & Switch.jpeg',
    description: 'Standard single wall socket and switch combination. Durable and easy to install.',
    rating: 0, reviews: 0, stockQuantity: 50,
  },
  {
    name: 'Single Sockets',
    brand: 'Generic',
    price: 1000,
    category: 'Switches & Sockets',
    image: 'Single Sockets .jpeg',
    description: 'Single wall sockets suitable for all standard electrical plugs in homes and offices.',
    rating: 0, reviews: 0, stockQuantity: 60,
  },
  {
    name: 'White Single Socket & Switch',
    brand: 'Generic',
    price: 1000,
    category: 'Switches & Sockets',
    image: 'White Single Socket & Switch .jpeg',
    description: 'Clean white single socket and switch plate. A classic finish that suits modern interiors.',
    rating: 0, reviews: 0, stockQuantity: 50,
  },

  // ─── DISTRIBUTION & PROTECTION ──────────────────────────────────────
  {
    name: 'AKT Extension Cable',
    brand: 'AKT',
    price: 1000,
    category: 'Distribution & Protection',
    image: 'AKT Extension .jpeg',
    description: 'AKT heavy-duty extension cable with multiple sockets. Suitable for home, office, and workshop use.',
    rating: 0, reviews: 0, stockQuantity: 30,
  },
  {
    name: 'AKT Extension Cord (Model 3)',
    brand: 'AKT',
    price: 1000,
    category: 'Distribution & Protection',
    image: 'Akt extension cord 3.jpeg',
    description: 'AKT multi-socket extension cord with surge protection built-in. Long cable for flexible placement.',
    rating: 0, reviews: 0, stockQuantity: 25,
  },
  {
    name: 'AKT Extension Cord',
    brand: 'AKT',
    price: 1000,
    category: 'Distribution & Protection',
    image: 'Akt extension cord.jpeg',
    description: 'Standard AKT extension cord with multiple power outlets. Heavy-duty cable for safe high-power use.',
    rating: 0, reviews: 0, stockQuantity: 30,
  },
  {
    name: 'Automatic Voltage Switcher',
    brand: 'Generic',
    price: 1000,
    category: 'Distribution & Protection',
    image: 'Automatic Voltage Switcher .jpeg',
    description: 'Automatic voltage switcher that switches power sources without manual intervention. Protects appliances from power fluctuations.',
    rating: 0, reviews: 0, stockQuantity: 15,
  },
  {
    name: 'Control Box',
    brand: 'Generic',
    price: 1000,
    category: 'Distribution & Protection',
    image: 'Control box.jpeg',
    description: 'Heavy-duty electrical control box for distribution boards and panel management.',
    rating: 0, reviews: 0, stockQuantity: 8,
  },
  {
    name: 'Fridge & TV Guard',
    brand: 'Generic',
    price: 1000,
    category: 'Distribution & Protection',
    image: 'Fridge and TV Guard.jpeg',
    description: 'Voltage protection device for refrigerators and televisions. Prevents damage from overvoltage and undervoltage.',
    rating: 0, reviews: 0, stockQuantity: 25,
  },
  {
    name: 'Mini Motor Siren',
    brand: 'Generic',
    price: 1000,
    category: 'Distribution & Protection',
    image: 'Mini Motor Siren.jpeg',
    description: 'Compact motor siren for alarm systems. Loud and attention-grabbing for security and alert systems.',
    rating: 0, reviews: 0, stockQuantity: 20,
  },
  {
    name: 'STONE TECH Voltage Protector',
    brand: 'STONE TECH',
    price: 1000,
    category: 'Distribution & Protection',
    image: 'STONE TECH voltage protector.jpeg',
    description: 'STONE TECH automatic voltage protector. Safeguards home appliances from unstable electrical supply.',
    rating: 0, reviews: 0, stockQuantity: 20,
  },
  {
    name: 'Surge TV Guard',
    brand: 'Generic',
    price: 1000,
    category: 'Distribution & Protection',
    image: 'Surge Tv GUARD.jpeg',
    description: 'Surge protection guard for televisions and electronics. Shields against power spikes and sudden voltage changes.',
    rating: 0, reviews: 0, stockQuantity: 20,
  },
  {
    name: 'TV Hanger',
    brand: 'Generic',
    price: 1000,
    category: 'Distribution & Protection',
    image: 'TV Hanger.jpeg',
    description: 'Universal TV wall-mount hanger compatible with most flat-screen TVs. Easy installation and adjustable tilt.',
    rating: 0, reviews: 0, stockQuantity: 25,
  },
  {
    name: 'Universal Travel Adapter',
    brand: 'Generic',
    price: 1000,
    category: 'Distribution & Protection',
    image: 'Universal Travel Adapter.jpeg',
    description: 'Compact universal travel adapter compatible with sockets worldwide. Great for travelers and international appliances.',
    rating: 0, reviews: 0, stockQuantity: 30,
  },
  {
    name: 'Universal Travel Adaptor (Model 2)',
    brand: 'Generic',
    price: 1000,
    category: 'Distribution & Protection',
    image: 'Universal Travel Adaptor 2.jpeg',
    description: 'Heavy-duty universal travel adaptor with multiple socket types and USB ports. Handles high wattage appliances safely.',
    rating: 0, reviews: 0, stockQuantity: 25,
  },
  {
    name: 'VOLTGUARD TV Guard',
    brand: 'VOLTGUARD',
    price: 1000,
    category: 'Distribution & Protection',
    image: 'VOLTGUARD TV Guard.jpeg',
    description: 'VOLTGUARD automatic voltage stabilizer and guard for televisions. Protects your screen from power surges.',
    rating: 0, reviews: 0, stockQuantity: 20,
  },
  {
    name: 'Zotek TV Guard',
    brand: 'Zotek',
    price: 1000,
    category: 'Distribution & Protection',
    image: 'Zotek TV guard.jpeg',
    description: 'Zotek TV guard with automatic cutoff for overvoltage and undervoltage. Reliable protection for your TV.',
    rating: 0, reviews: 0, stockQuantity: 20,
  },

  // ─── CABLES & WIRES ──────────────────────────────────────────────────
  {
    name: 'Cables & Wires Bundle',
    brand: 'Generic',
    price: 1000,
    category: 'Cables & Wires',
    image: 'Cables and Wires .jpeg',
    description: 'Assorted electrical cables and wires for residential and commercial installations. Various gauges available.',
    rating: 0, reviews: 0, stockQuantity: 50,
  },
  {
    name: 'High-Voltage LED Battery (Large)',
    brand: 'Generic',
    price: 1000,
    category: 'Cables & Wires',
    image: 'High-Voltage Led Battery.jpeg',
    description: 'High-capacity LED battery pack for powering large LED light setups without direct power connection.',
    rating: 0, reviews: 0, stockQuantity: 10,
  },
  {
    name: 'High-Voltage Lead Battery',
    brand: 'Generic',
    price: 1000,
    category: 'Cables & Wires',
    image: 'High-Voltage lead Battery.jpeg',
    description: 'Heavy-duty high-voltage lead-acid battery for solar systems, inverters, and backup power setups.',
    rating: 0, reviews: 0, stockQuantity: 10,
  },
  {
    name: 'Wires & Cables',
    brand: 'Generic',
    price: 1000,
    category: 'Cables & Wires',
    image: 'Wires and Cables .jpeg',
    description: 'Premium quality electrical wires and cables for all types of electrical installation work.',
    rating: 0, reviews: 0, stockQuantity: 50,
  },

  // ─── HOME APPLIANCES ─────────────────────────────────────────────────
  {
    name: 'Binatone Dry Iron',
    brand: 'Binatone',
    price: 1000,
    category: 'Home Appliances',
    image: 'Binatone Dry Iron.jpeg',
    description: 'Binatone dry iron with non-stick soleplate and adjustable temperature control. Lightweight and efficient.',
    rating: 0, reviews: 0, stockQuantity: 20,
  },
  {
    name: 'Bonatone Dry Iron (Model 2)',
    brand: 'Bonatone',
    price: 1000,
    category: 'Home Appliances',
    image: 'Bonatone Dry Iron 2.jpeg',
    description: 'Bonatone dry iron with smooth gliding plate and rapid heat-up technology for wrinkle-free clothes.',
    rating: 0, reviews: 0, stockQuantity: 20,
  },
  {
    name: 'PHILIPS Dry Iron',
    brand: 'PHILIPS',
    price: 1000,
    category: 'Home Appliances',
    image: 'PHILIPS Dry Iron.jpeg',
    description: 'PHILIPS branded dry iron with precision temperature control and durable soleplate.',
    rating: 0, reviews: 0, stockQuantity: 15,
  },
  {
    name: 'QASA Dry Iron',
    brand: 'QASA',
    price: 1000,
    category: 'Home Appliances',
    image: 'QASA Dry Iron .jpeg',
    description: 'QASA dry iron with easy-grip handle, variable temperature settings, and non-stick coating.',
    rating: 0, reviews: 0, stockQuantity: 20,
  },
  {
    name: 'Electric Kettle',
    brand: 'Generic',
    price: 1000,
    category: 'Home Appliances',
    image: 'Electric Kettle .jpeg',
    description: 'Fast-boiling electric kettle with auto shut-off and 1.8L capacity. Perfect for tea, coffee, and quick hot water.',
    rating: 0, reviews: 0, stockQuantity: 20,
  },
  {
    name: 'Mega Flash Electric Kettle',
    brand: 'Mega Flash',
    price: 1000,
    category: 'Home Appliances',
    image: 'Mega Flash Electric Kettle .jpeg',
    description: 'Mega Flash electric kettle with rapid boil technology, 1.8L capacity, and safety auto-shutoff.',
    rating: 0, reviews: 0, stockQuantity: 15,
  },
  {
    name: 'High Power Blender / Grinder',
    brand: 'Generic',
    price: 1000,
    category: 'Home Appliances',
    image: 'High Power Blender or Grinder.jpeg',
    description: 'High-powered blender and grinder for food processing. Handles tough ingredients with ease.',
    rating: 0, reviews: 0, stockQuantity: 15,
  },
  {
    name: 'QASA Blender / Grinder',
    brand: 'QASA',
    price: 1000,
    category: 'Home Appliances',
    image: 'QASA Blender or Grinder.jpeg',
    description: 'QASA multi-purpose blender and grinder with stainless steel blades and multiple speed settings.',
    rating: 0, reviews: 0, stockQuantity: 12,
  },
  {
    name: 'Sandwich Maker',
    brand: 'Generic',
    price: 1000,
    category: 'Home Appliances',
    image: 'Sandwich Maker.jpeg',
    description: 'Non-stick sandwich and toast maker. Heats up quickly, easy to clean, and great for quick snacks.',
    rating: 0, reviews: 0, stockQuantity: 15,
  },
  {
    name: 'Gas Burner',
    brand: 'Generic',
    price: 1000,
    category: 'Home Appliances',
    image: 'Gas burner .jpeg',
    description: 'Portable gas burner for cooking. Compact size, easy ignition, and works with standard gas cylinders.',
    rating: 0, reviews: 0, stockQuantity: 20,
  },
  {
    name: 'Table Gas Cooker (THERMACOOL)',
    brand: 'THERMACOOL',
    price: 1000,
    category: 'Home Appliances',
    image: 'Table Gas Cooker THERMACOOL.jpeg',
    description: 'THERMACOOL 2-burner table top gas cooker. Durable, easy to use, and suitable for everyday cooking.',
    rating: 0, reviews: 0, stockQuantity: 10,
  },
  {
    name: 'HI-Fi Multimedia Speaker',
    brand: 'Generic',
    price: 1000,
    category: 'Home Appliances',
    image: 'HI Fi Multimedia Speaker.jpeg',
    description: 'HI-Fi multimedia speaker with rich bass and clear treble. Compatible with USB, FM, and Bluetooth.',
    rating: 0, reviews: 0, stockQuantity: 15,
  },
  {
    name: 'Home Theater System',
    brand: 'Generic',
    price: 1000,
    category: 'Home Appliances',
    image: 'Home theater .jpeg',
    description: 'Complete home theater system with surround sound. Immersive audio experience for movies and music.',
    rating: 0, reviews: 0, stockQuantity: 8,
  },
  {
    name: 'Weight Checker',
    brand: 'Generic',
    price: 1000,
    category: 'Home Appliances',
    image: 'Weight Checker.jpeg',
    description: 'Digital weight checker / bathroom scale. Clear LCD display with accurate readings up to 180kg.',
    rating: 0, reviews: 0, stockQuantity: 20,
  },
  {
    name: 'Wireless Clipper',
    brand: 'Generic',
    price: 1000,
    category: 'Home Appliances',
    image: 'Wireless Clipper.jpeg',
    description: 'Professional wireless hair clipper with adjustable blade settings and rechargeable battery. Cordless for easy use.',
    rating: 0, reviews: 0, stockQuantity: 20,
  },
];

async function seedProducts() {
  try {
    console.log('Connecting to MongoDB...');
    await mongoose.connect(MONGO_URI);
    console.log('✅ Connected to MongoDB!');

    let added = 0;
    let skipped = 0;

    for (const product of customProducts) {
      const exists = await Product.findOne({ name: product.name });
      if (exists) {
        console.log(`⏭️  Skipped (already exists): ${product.name}`);
        skipped++;
      } else {
        await Product.create(product);
        console.log(`✅ Added: ${product.name}`);
        added++;
      }
    }

    console.log(`\n🎉 Done! Added ${added} new products. Skipped ${skipped} duplicates.`);
    console.log(`📝 Remember: All new products have placeholder price ₦1,000. Update them in the Inventory tab!`);
    process.exit(0);
  } catch (err) {
    console.error('❌ Error:', err.message);
    process.exit(1);
  }
}

seedProducts();
